sudo: required
language: node_js
install:
  - npm install -g codecov
  - npm install -g istanbul
node_js:
  - "5.0"
  - "4.0"
script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -R spec
  - codecov